
spring:
  boot:
    admin:
      context-path: /admin

  application:
    name: discovery-service
eureka:
  client:
    register-with-eureka: false
  instance:
    prefer-ip-address: true
server:
  port: 8761


