#spring.cloud.config.server.git.uri=file:///Users/charlvictor/

spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/{application}


server:
  port: 8888